version: '3.8'

services:
  avatar-creator:
    image: howieduhzit/avatar-creator:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVICE_FQDN_AVATAR_CREATOR_3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
