name: Main

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          lfs: true

      - name: "NPM Install, Build, and Cache"
        id: npm-install-build-and-cache
        uses: ./.github/actions/npm-install-build-and-cache

  type-check:
    name: Type Check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Type Check
        run: npm run type-check-all

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: "Retrieve Dependencies and Build Artifacts"
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Lint
        run: npm run lint-all

  summary:
    name: Summary
    needs: [build, type-check, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "Build: ${{ needs.build.result }}"
          echo "Type Check: ${{ needs.type-check.result }}"
          echo "Lint: ${{ needs.lint.result }}"

  release:
    name: Release
    needs: [summary]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Determine if version differs from npm
        id: check_version
        run: |
          ./scripts/check-version-changed.sh

      - name: "Retrieve Dependencies and Build Artifacts"
        if: steps.check_version.outputs.should_release == 'true'
        id: retrieve-deps-and-build
        uses: ./.github/actions/retrieve-deps-and-build

      - name: Configure Git
        if: steps.check_version.outputs.should_release == 'true'
        run: |
          git config --local user.email "release-action@github.com"
          git config --local user.name "GitHub Release Action"

      - name: Release if version changed
        if: steps.check_version.outputs.should_release == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ./scripts/release-new-version.sh
