name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version number (e.g., 0.1.6, 0.2.0, 1.0.0)"
        required: true
        type: string

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          lfs: true

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Build package with caching
        uses: ./.github/actions/npm-install-build-and-cache

      - name: Configure Git
        run: |
          git config --local user.email "release-action@github.com"
          git config --local user.name "GitHub Release Action"

      - name: Run release script
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NEW_VERSION: ${{ github.event.inputs.version }}
        run: |
          NPM_TOKEN="$NPM_TOKEN" ./scripts/release-new-version.sh "$NEW_VERSION"

      - name: Push changes and tags
        run: |
          git push origin main
          git push --tags
